name: Auto Gen baike.txt
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Python gen baike
        run: python3 .github/scripts/gen_baike.py

      - name: Auto commit baike.txt
        run: |
          git config --global user.name "WikiBot"
          git config --global user.email "bot@bgpwiki.dev"
          git add baike.txt
          git diff --cached --quiet || git commit -m "Auto update baike.txt"
          git push
